### PR TITLE
Sponsor Section created with additional page 

### PR DESCRIPTION
**Pull request by Tushar98644**

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
Screenshot 2022-12-15 at 11 16 02 PM
Please come up with a design first. once approved add it for mobile , tab, and web view using the same folder structure.

**Review by tanmoy27112000 — CHANGES_REQUESTED** [review]
First create a design and then you start working on it

**Comment by Tushar98644** [comment]
> First create a design and then you start working on it

i shall go with the same design but i will optimise  it for tablet and laptop view......is that fine?

**Comment by tanmoy27112000** [comment]
Create a grid view like we have in the member page and add dummy companies. add a sponsor tab in the nav bar

**Comment by Tushar98644** [comment]
> Create a grid view like we have in the member page and add dummy companies. add a sponsor tab in the nav bar

ok...will do it by tomorrow

**Pull request closed without merging**
